### PR TITLE
dis/analysis/jets.cxx: update from the latest code

### PR DESCRIPTION
**Pull request by veprbl**
Updates jets benchmark

### CODE REVIEW

**Review by torrijeske — APPROVED** [review]

**Comment by bspage912** [comment]
Hi All, not sure what prompted this update but the example I had in the snippets repository wasn't meant to be the benchmark plot code. I have a more extensive benchmark macro that is basically ready to roll out now. I can send it Monday (or maybe tonight if I have time) - @torrijeske can you send me the link to the form you had set up for this?

**Review by bspage912 — APPROVED** [review]
Looks like this is basically a copy of what is in the eic/image_browser repository so I am fine. 

Dmitry, can you help me understand how this benchmark differs from what @torrijeske does in the image browser? Will this run after every pushed change to eicrecon for example?

Also, how do we plan on keeping the code in these two repositories in sync?

**Comment by torrijeske** [comment]
As far as keeping the repositories in sync, I’d rather the macros go to the benchmarks repository and I can pull them from there before generating the images. I just put the macro in eic/image_browser temporarily.

From: Brian Page ***@***.***>
Date: Friday, July 19, 2024 at 1:17 PM
To: eic/physics_benchmarks ***@***.***>
Cc: Torri Jeske ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [eic/physics_benchmarks] dis/analysis/jets.cxx: update from the latest code (PR #13)

@bspage912 approved this pull request.

Looks like this is basically a copy of what is in the eic/image_browser repository so I am fine.

Dmitry, can you help me understand how this benchmark differs from what @torrijeske<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_torrijeske&d=DwMFaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=0aQ6wxy3M6hRyMbqpqoqoQ&m=-8Q0hrmZ4SJDEQFWJGMItXhgRSYoooXODnhjLWU_ueyr_rCJy2ThJ7yAfKVYxEhB&s=RmqH1J8Vn58jQ6GTmeMdZhbf5wI6KyegI_evkiMq3C0&e=> does in the image browser? Will this run after every pushed change to eicrecon for example?

Also, how do we plan on keeping the code in these two repositories in sync?

**Comment by veprbl** [comment]
Results on CI like https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/3532264/artifacts/browse/results/epic_craterlake/dis/18on275/minQ2=1000/jets/ look good, let's merge.

**Pull request merged**
